# Project information
site_name: Burst Wiki
site_description: The Burstcoin Wiki
site_author: The Burst Apps Team
site_url: https://burst-apps-team.github.io/burst-wiki

# Repository (Commented as it is private)
repo_name: burst-wiki
repo_url: https://github.com/burst-apps-team/burst-wiki

# Theme
theme:
  name: 'material'
  #favicon: assets/img/favicon.ico
  #logo: assets/img/logo.png
  feature:
    tabs: true
  palette:
    primary: blue
    accent: blue

# Options
extra:
  social:
    - type: github-alt
      link: https://github.com/harry1453

# Page tree
pages:
  - Home: main-page.md
  - 500k HF Checklist: 500k-hf-checklist.md
  - Activate Burst Account: activate-burst-account.md
  - Alias System: alias-system.md
  - Arbitrary Messages: arbitrary-messages.md
  - Asset Exchange: asset-exchange.md
  - Automated Transaction: automated-transaction.md
  - Block Reward: block-reward.md
  - BRS Configuration File: brs-default-properties-configuration-file.md
  - BRS Docker Installation: brs-docker-installation.md
  - BRS Linux Installation: brs-linux-installation.md
  - BRS MacOS Installation: brs-maxos-installation.md
  - BRS Windows Installation: brs-windows-installation.md
  - Burst Blockchain: burst-blockchain.md
  - Burstcoin Reference Software: burst-reference-software.md
  - Burst Services: burst-services.md
  - Burst Software: burst-software.md
  - Burst Support for ERC20 tokens: burst-support-for-erc20-tokens.md
  - Burst Who's Who: burst-who-s-who.md
  - Burst Wiki: burst-wiki.md
  - CIP: cip.md
  - Colored Coins: colored-coins.md
  - Contribute: contribute.md
  - Current Features: current-features.md
  - Engraver - How to compile from source: engraver---how-to-compile-from-source.md
  - Exchanges: exchanges.md
  - FAQ: faq.md
  - Getting Started: getting-started.md
  - History of Burst: history-of-burst.md
  - Internal AT and Escrow Account: internal-at-and-escrow-account.md
  - Join Us: join-us-.md
  - List of Burst Related Websites: list-of-burst-related-websites.md
  - List of International Burst Websites: list-of-international-burst-websites.md
  - MacOS Burst Wallet Installation: macos-burst-wallet-installation.md
  - Marketplace: marketplace.md
  - Mining: mining.md
  - Mobile App: mobile-app.md
  - Mortimer: mortimer.md
  - NXT default properties configuration file: nxt-default-properties-configuration-file.md
  - Offline Transaction Signing: offline-transaction-signing.md
  - Pchains: pchains.md
  - Plotting Software: plot-software.md
  - Plotter: plotter.md
  - Plotting: plotting.md
  - PoCC Mobile App: pocc-mobile-app.md
  - Proof of Capacity: proof-of-capacity.md
  - Publications - Burst Cryptocurrency News: publications--burst--cryptocurrency-news-.md
  - Publications - Burst Gneral: publications--burst--general-.md
  - Publications - Burst Commercial: publications-burst-commercial-.md
  - Publications - Burst Cryptonews: publications-burst-cryptonews-.md
  - Publications - Burst News: publications-burst-news-.md
  - Publications - Burst Research: publications-burst-research-.md
  - Publications - Burst: publications-burst.md
  - Qbundle: qbundle.md
  - Reward Assignment: reward-assignment.md
  - RS Address Format: rs-address-format.md
  - Sandbox: sandbox.md
  - Scavenger - How to compile from source: scavenger---how-to-compile-from-source.md
  - Secure your Burst: secure-your-burst.md
  - Slot-Based Transaction Fees: slot-based-transaction-fees.md
  - Smart Contract: smart-contract.md
  - Softfork Wishlist: softfork-wishlist.md
  - Style Guide: style-guide.md
  - Team Applications: team-applications.md
  - Team Support: team-support.md
  - Technical Information about Mining and Block Forging: technical-information-about-mining-and-block-forging.md
  - Technical Information to create plot files: technical-information-to-create-plot-files.md
  - Testnet: testnet.md
  - The Burst API: the-burst-api.md
  - The Burst API Examples: the-burst-api-examples.md
  - TODO: todo.md
  - Transaction and Fee Types: transaction-and-fee-types.md
  - Whitepapers: whitepaper-burst.md
  - Wikipedia - Burstcoin: wikipedia-burstcoin.md
  - Windows Burst Wallet Installation: windows-burst-wallet-installation.md
